# Generated by Django 3.0.4 on 2020-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(default=None, max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
