# Generated by Django 3.0.4 on 2020-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200323_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
