# Generated by Django 3.0.4 on 2020-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200325_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('1', 'Broodje van de week'), ('2', 'Broodjes'), ('3', 'Drinken'), ('4', "Extra's")], default='Broodjes', max_length=50),
        ),
    ]
