# Generated by Django 3.0.4 on 2020-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200331_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
