# Generated by Django 3.0.4 on 2020-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200331_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broodje_vdw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('1', 'Broodjes'), ('2', 'Drinken'), ('3', "Extra's")], default='2', max_length=50),
        ),
    ]
