# Generated by Django 3.0.4 on 2020-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200331_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='broodje_vdw',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
