# Generated by Django 3.0.4 on 2020-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20200406_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
