# Generated by Django 3.0.4 on 2020-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200411_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
