# Generated by Django 3.0.4 on 2020-04-16 10:59

import Web.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20200411_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(default=None, storage=Web.custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='broodje_vdw',
            name='image',
            field=models.ImageField(default=None, storage=Web.custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
