# Generated by Django 3.0.4 on 2020-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20200416_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
