# Generated by Django 3.0.4 on 2020-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_couponcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('broodjes', 'Broodjes'), ('drinken', 'Drinken'), ('extras', "Extra's")], default='2', max_length=50),
        ),
    ]
