# Generated by Django 3.0.4 on 2020-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20200505_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='broodje_vdw',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='couponcodes',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
