# Generated by Django 3.0.4 on 2020-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20200515_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='spiciness_category',
            field=models.CharField(choices=[('1', 'Broodjes'), ('2', 'Drinken'), ('3', "Extra's")], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broodje_vdw',
            name='spiciness_category',
            field=models.CharField(choices=[('1', 'Broodjes'), ('2', 'Drinken'), ('3', "Extra's")], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='broodje_vdw',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
