# Generated by Django 3.0.4 on 2020-07-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20200715_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='spiciness_category',
            field=models.CharField(choices=[('1', 'Geen (mild)'), ('2', 'Pittig'), ('3', 'Extra pittig')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='broodje_vdw',
            name='spiciness_category',
            field=models.CharField(choices=[('1', 'Geen (mild)'), ('2', 'Pittig'), ('3', 'Extra pittig')], default='1', max_length=50),
        ),
    ]
